// Code generated by hertz generator.

package main

import (
	"web_chat/biz/config"
	"web_chat/biz/db"
	"web_chat/biz/middleware"
	"web_chat/biz/util/logger"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/hertz-contrib/binding/go_playground"
	"github.com/hertz-contrib/logger/accesslog"
)

func main() {
	logger.Init()
	config.Init()
	db.Init()

	vd := go_playground.NewValidator()

	h := server.Default(
		server.WithHostPorts("0.0.0.0:8080"),
		server.WithCustomValidator(vd),
	)

	h.Use(middleware.RecoveryMiddleware())
	h.Use(middleware.TraceContextMW())
	h.Use(
		accesslog.New(
			accesslog.WithAccessLogFunc(hlog.CtxInfof),
			accesslog.WithFormat("${status} - ${latency} ${method} ${path} ${queryParams}"),
		),
	)

	// h.Use(
	// 	cors.New(cors.Config{
	// 		AllowCredentials: false,
	// 		MaxAge:           12 * time.Hour,
	// 	},
	// 	),
	// )

	h.Use(middleware.SessionMiddleware())

	register(h)
	h.Spin()
}
