// Code generated by hertz generator.

package main

import (
	handler "web_chat/biz/handler"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	r.POST("/login", handler.Login)

	root := r.Group("/", handler.AccountIDMiddleware())
	{
		root.POST("/logout", handler.Logout)

		authGroup := root.Group("/", handler.AccountStatusMiddleware())
		{
			authGroup.POST("/password/update", handler.UpdatePassword)
		}
	}
}
