// Code generated by hertz generator.

package main

import (
	handler "web_chat/biz/handler"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	r.POST("/login", handler.Login)
	r.GET("/login", handler.LoginPage)

	root := r.Group("/", handler.AccountIDMiddleware())
	{
		root.POST("/logout", handler.Logout)

		authGroup := root.Group("/", handler.AccountStatusMiddleware())
		{
			authGroup.POST("/password/update", handler.UpdatePassword)

			chat := authGroup.Group("/chat", handler.ChatLimitMiddleware()...)
			{
				chat.POST("/stream", handler.StreamChat)
			}
		}
	}

	// move into root after test
	r.GET("/index/home", handler.HomePage)
	r.GET("/index/readme", handler.ReadMePage)
	r.GET("/index/chat", handler.ChatPage)
	r.GET("/index/password_update")
}
