// Code generated by hertz generator.

package main

import (
	handler "web_chat/biz/handler"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	root := r.Group("/", handler.RootMiddleware()...)
	{
		root.POST("/login", handler.Login)
		root.GET("/login", handler.LoginPage)

		authGroup := root.Group("/", handler.AuthMiddleware()...)
		{
			authGroup.POST("/logout", handler.Logout)
			authGroup.POST("/password/update", handler.UpdatePassword)

			chat := authGroup.Group("/chat", handler.ChatLimitMiddleware()...)
			{
				chat.POST("/create", handler.CreateChat)
				chat.GET("/stream", handler.StreamChat)
			}

			index := authGroup.Group("/index")
			{
				index.GET("/home", handler.HomePage)
				index.GET("/readme", handler.ReadMePage)
				index.GET("/chat", handler.ChatPage)
				index.GET("/password_update", handler.PasswordUpdatePage)
			}
		}
	}
}
